name: Deploy to AWS S3

on:
  push:
    branches:
      - master
      - release/**

env:
  project-name: Photorunctin-Eye

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Package Install
        run: npm install

      - name: Build
        run: npm run generate

      - name: Publish to AWS S3 & CloudFront Cache Clear
        uses: opspresso/action-s3-sync@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-1'
          FROM_PATH: './dist'
          DEST_PATH: 's3://photoruction-eye/'
          OPTIONS: "--acl public-read --delete"
